services:
  ENV-ibt-marketing-ms:
    container_name: ENV-ibt-marketing-ms
    image: registry.ibt.ru:5050/ibt-marketing-ms:${TAG}
    restart: always
    env_file:
      - /home/iBT.studio/ENV/svc/ibt-marketing-ms/.env
    environment:
      - SENTRY_RELEASE=${SENTRY_RELEASE}
      - PHP_SOCK_FILE=/sockets/ENV-ibt-marketing-ms_php
    volumes:
      - /sockets/:/sockets/
      - /home/iBT.studio/ENV/data/jwt_key/:/var/www/jwt_key/
      - /home/iBT.studio/ENV/svc/ibt-marketing-ms/.env:/var/www/.env
      - /home/iBT.studio/ENV/svc/conf/php.ini:/usr/local/etc/php/php.ini
      - /home/iBT.studio/ENV/svc/ibt-marketing-ms/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    hostname: ibt-marketing-ms.ENV
    networks:
      ENV.svc.cluster.local:
        aliases:
          - ibt-marketing-ms.ENV.svc.cluster.local
    extra_hosts:
      - "mysql-master:host-gateway"
      - "redis-ENV:host-gateway"
